=== Danil0v3s/mmo-csharp/Map.Server/config/battle/battle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./battle.schema.json",
  "title": "rAthena battle.conf \u2014 core battle knobs",
  "description": "Generated by Tools.RathenaImporter from rAthena .conf. Each property\u0027s description is the inline comment from the source file.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "enable_baseatk": {
      "type": "integer",
      "description": "--------------------------------------------------------------\nrAthena Battle Configuration File\nOriginally Translated by Peter Kieser \u003Cpfak@telus.net\u003E\nMade in to plainer English by Ancyker\n--------------------------------------------------------------\nNote 1: Value is a config switch (on/off, yes/no or 1/0)\nNote 2: Value is in percents (100 means 100%)\nNote 3: Value is a bit field. If no description is given,\nassume unit types (1: Pc, 2: Mob, 4: Pet, 8: Homun, 16: Mercenary, 128: NPC, 512: Elemental)\n--------------------------------------------------------------\nWho should have a baseatk value (makes str affect damage)? (Note 3)",
      "default": 9
    },
    "enable_baseatk_renewal": {
      "type": "integer",
      "default": 671
    },
    "enable_perfect_flee": {
      "type": "integer",
      "description": "Who can have perfect flee? (Note 3)",
      "default": 1
    },
    "enable_critical": {
      "type": "integer",
      "description": "Who can have critical attacks? (Note 3)\n(Note that there are some skills that always do critical hit regardless of this)",
      "default": 17
    },
    "mob_critical_rate": {
      "type": "integer",
      "description": "Critical adjustment rate for non-players (Note 2)",
      "default": 100
    },
    "critical_rate": {
      "type": "integer",
      "default": 100
    },
    "attack_walk_delay": {
      "type": "integer",
      "description": "Should normal attacks give you a walk delay? (Note 3)\nIf no, characters can move as soon as they start an attack (attack animation\nor walk animation may be omitted client-side, causing cropped attacks or\nmonsters that teleport to you)\nOtherwise, the delay is equal to the \u0027attack animation\u0027 (amotion)",
      "default": 15
    },
    "pc_damage_walk_delay_rate": {
      "type": "integer",
      "description": "Move-delay adjustment after being hit. (Note 2)\nThe \u0027can\u0027t walk\u0027 delay after being hit is calculated as a percentage of the damage animation duration.\nNOTE: Only affects the normal delay from a single attack, not the delay added by the multihit_delay option below.",
      "default": 20
    },
    "damage_walk_delay_rate": {
      "type": "integer",
      "default": 100
    },
    "multihit_delay": {
      "type": "integer",
      "description": "Move-delay adjustment for multi-hitting attacks.\nWhen hit by a multi-hitting skill like Lord of Vermillion or Jupitel Thunder, characters will be\nunable to move for an additional \u0022(number of hits -1) * multihit_delay\u0022 milliseconds.\n80 is the setting that feels like Aegis (vs Sonic Blows)\n230 is the setting that makes walkdelay last until the last hit (vs Jupitel thunder)",
      "default": 80
    },
    "player_damage_delay_rate": {
      "type": "integer",
      "description": "Damaged delay rate for players (Note 2)\n(Setting to no/0  will be like always endure)",
      "default": 100
    },
    "undead_detect_type": {
      "type": "integer",
      "description": "Should race or element be used to consider someone undead?\n0 = element undead\n1 = race undead\n2 = both (either one works)",
      "default": 0
    },
    "attribute_recover": {
      "type": "boolean",
      "description": "Does HP recover if hit by an attribute that\u0027s same as your own? (Note 1)",
      "default": false
    },
    "min_hitrate": {
      "type": "integer",
      "description": "What is the minimum and maximum hitrate of normal attacks?",
      "default": 5
    },
    "max_hitrate": {
      "type": "integer",
      "default": 100
    },
    "agi_penalty_type": {
      "type": "integer",
      "description": "Type of penalty that is applied to FLEE when more than agi_penalty_count monsters are targetting player\n0 = no penalty is applied\n1 = agi_penalty_num is reduced from FLEE as a %\n2 = agi_penalty_num is reduced from FLEE as an exact amount",
      "default": 1
    },
    "agi_penalty_target": {
      "type": "integer",
      "description": "When agi penalty is enabled, to whom it should apply to? (Note 3)\nBy default, only players get the penalty.",
      "default": 1
    },
    "agi_penalty_count": {
      "type": "integer",
      "description": "Amount of enemies required to be targetting player before FLEE begins to be penalized",
      "default": 3
    },
    "agi_penalty_num": {
      "type": "integer",
      "description": "Amount of FLEE penalized per each attacking monster more than agi_penalty_count",
      "default": 10
    },
    "vit_penalty_type": {
      "type": "integer",
      "description": "Type of penalty that is applied to both equipment and vit DEF when more than vit_penalty_count monsters are targetting player\n0 = no penalty is applied\n1 = vit_penalty_num is reduced from DEF as a %\n2 = vit_penalty_num is reduced from DEF as an exact amount",
      "default": 1
    },
    "vit_penalty_target": {
      "type": "integer",
      "description": "When vit penalty is enabled, to whom it should apply to? (Note 3)\nBy default, only players get the penalty.",
      "default": 1
    },
    "vit_penalty_count": {
      "type": "integer",
      "description": "Amount of enemies required to be targetting player before defense begins to be penalized",
      "default": 3
    },
    "vit_penalty_num": {
      "type": "integer",
      "description": "Amount of VIT defense penalized per each attacking monster more than vit_penalty_count",
      "default": 5
    },
    "weapon_defense_type": {
      "type": "integer",
      "description": "Use alternate method of DEF calculation for physical attacks.\nWith 0, disabled (use normal def% reduction with further def2 reduction)\nAt 1 or more defense is subtraction of (DEF * value).\neg: 10 \u002B 50 def becomes 0 \u002B (10*type \u002B 50)",
      "default": 0
    },
    "magic_defense_type": {
      "type": "integer",
      "description": "MDEF\u201A same as above. (MDEF * value)",
      "default": 0
    },
    "attack_direction_change": {
      "type": "integer",
      "description": "Change attacker\u0027s direction to face opponent on every attack? (Note 3)\nNOTE: On official servers knockback of some skills like Firewall is always based on the\nlast direction walked. Even when attacking in a completely different direction, the\nknockback direction won\u0027t change, so e.g. if you walk north and then attack an enemy to\nthe south you will still be knocked back to the south by Firewall. Immobile monsters\nwill always be knocked back to the south as their default direction is north.",
      "default": 0
    },
    "attack_attr_none": {
      "type": "integer",
      "description": "For those who is set, their innate attack element is \u0022not elemental\u0022\n(100% versus on all defense-elements) (Note 3)\nNOTE: This is the setting that makes it so non-players can hit for full\ndamage against Ghost-type targets with normal attacks (eg: vs. Ghostring).",
      "default": 14
    },
    "equip_natural_break_rate": {
      "type": "integer",
      "description": "Rate at which equipment can break (base rate before it\u0027s modified by any skills)\n1 = 0.01% chance. Default for official servers: 0",
      "default": 0
    },
    "equip_self_break_rate": {
      "type": "integer",
      "description": "Overall rate of which your own equipment can break. (Note 2)\nThis rate affects penalty breaking rate of skills such as power-thrust and your natural breaking rate\n(from equip_natural_break_rate). If a Sage\u0027s endow skill fails and this is above 0, the selected char\u0027s\nweapon will be broken.",
      "default": 100
    },
    "equip_skill_break_rate": {
      "type": "integer",
      "description": "Overall rate at which you can break target\u0027s equipment. (Note 2)\nThis affects the behaviour of skills like acid terror and meltdown",
      "default": 100
    },
    "delay_battle_damage": {
      "type": "boolean",
      "description": "Should damage have a delay before it is applied? (Note 1)\nSome skills might not have a delay by default regardless of this setting.\nThe official setting is yes, even thought it degrades performance a bit.",
      "default": true
    },
    "synchronize_damage": {
      "type": "boolean",
      "description": "Should the damage timing be synchronized between the client and server? (Note 1)\nThis is not official behavior, but it should remove the position lag after being hit by a monster.\nThis setting only affects normal monster attacks and takes priority over \u0022delay_battle_damage\u0022.\nMany skills show their damage immediately, so setting \u0022delay_battle_damage\u0022 to \u0022no\u0022 at the same\ntime might improve the experience further, but will not work for all skills.\nTired of Dark Illusion hitting you 5 seconds too late? Then turn this on.",
      "default": false
    },
    "arrow_decrement": {
      "type": "integer",
      "description": "Are arrows/ammo consumed when used on a bow/gun?\n0 = No\n1 = Yes\n2 = Yes even for skills that do not specify arrow consumption when said\nskill is weapon-based and used with ranged weapons (auto-guesses which\nskills should consume ammo when it\u0027s acquired via a card or plagiarize)",
      "default": 1
    },
    "ammo_unequip": {
      "type": "boolean",
      "description": "Should ammo be unequipped when unequipping a weapon?\nOfficial behavior is \u0022yes\u0022.",
      "default": true
    },
    "ammo_check_weapon": {
      "type": "boolean",
      "description": "Should a suitable weapon be equipped when equipping ammo?\nOfficial behavior is \u0022yes\u0022.",
      "default": true
    },
    "autospell_check_range": {
      "type": "boolean",
      "description": "Should the item script bonus \u0027Autospell\u0027 check for range/obstacles before casting?\nOfficial behavior is \u0022no\u0022, setting this to \u0022yes\u0022 will make skills use their defined\nrange. For example, Sonic Blow requires a 2 cell distance before autocasting is allowed.\nThis setting also affects autospellwhenhit.",
      "default": false
    },
    "knockback_left": {
      "type": "boolean",
      "description": "If both the attacker and the target are on the same tile, should the target be knocked back to the left?\nOfficial behavior is \u0022yes\u0022, setting this to \u0022no\u0022 will knock the target back behind the attacker.",
      "default": true
    },
    "warg_can_falcon": {
      "type": "boolean",
      "description": "Can players use Falcons and Wargs at the same time? (Note 1)\nThis is not allowed on official servers.",
      "default": false
    },
    "snap_dodge": {
      "type": "boolean",
      "description": "Should the target be able of dodging damage by snapping away to the edge of the screen?\nOfficial behavior is \u0022no\u0022",
      "default": false
    },
    "break_mob_equip": {
      "type": "boolean",
      "description": "Grant player skills/items the ability to \u0022break\u0022 non-player equipment. (Note 1)\nThis will effectively apply the strip equip effect to the non-player target.\nNOTE: WS_MELTDOWN is exempt from this check when disabled.\nOfficial: no",
      "default": false
    }
  }
}

=== Danil0v3s/mmo-csharp/Map.Server/config/battle/battle.json
{
  "$schema": "./battle.schema.json",
  "enable_baseatk": 9,
  "enable_baseatk_renewal": 671,
  "enable_perfect_flee": 1,
  "enable_critical": 17,
  "mob_critical_rate": 100,
  "critical_rate": 100,
  "attack_walk_delay": 15,
  "pc_damage_walk_delay_rate": 20,
  "damage_walk_delay_rate": 100,
  "multihit_delay": 80,
  "player_damage_delay_rate": 100,
  "undead_detect_type": 0,
  "attribute_recover": false,
  "min_hitrate": 5,
  "max_hitrate": 100,
  "agi_penalty_type": 1,
  "agi_penalty_target": 1,
  "agi_penalty_count": 3,
  "agi_penalty_num": 10,
  "vit_penalty_type": 1,
  "vit_penalty_target": 1,
  "vit_penalty_count": 3,
  "vit_penalty_num": 5,
  "weapon_defense_type": 0,
  "magic_defense_type": 0,
  "attack_direction_change": 0,
  "attack_attr_none": 14,
  "equip_natural_break_rate": 0,
  "equip_self_break_rate": 100,
  "equip_skill_break_rate": 100,
  "delay_battle_damage": true,
  "synchronize_damage": false,
  "arrow_decrement": 1,
  "ammo_unequip": true,
  "ammo_check_weapon": true,
  "autospell_check_range": false,
  "knockback_left": true,
  "warg_can_falcon": false,
  "snap_dodge": false,
  "break_mob_equip": false
}
