=== Danil0v3s/mmo-csharp/Map.Server/config/battle/client.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./client.schema.json",
  "title": "rAthena client.conf",
  "description": "Generated by Tools.RathenaImporter from rAthena .conf. Each property\u0027s description is the inline comment from the source file.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "min_chat_delay": {
      "type": "integer",
      "description": "--------------------------------------------------------------\nrAthena Battle Configuration File\nOriginally Translated by Peter Kieser \u003Cpfak@telus.net\u003E\nMade in to plainer English by Ancyker\n--------------------------------------------------------------\nNote 1: Value is a config switch (on/off, yes/no or 1/0)\nNote 2: Value is in percents (100 means 100%)\nNote 3: Value is a bit field. If no description is given,\nassume unit types (1: Pc, 2: Mob, 4: Pet, 8: Homun, 16: Mercenary)\n--------------------------------------------------------------\nMinimum delay between whisper/global/party/guild messages (in ms)\nMessages that break this threshold are silently omitted.",
      "default": 0
    },
    "min_hair_style": {
      "type": "integer",
      "description": "Valid range of dyes and styles on the client.",
      "default": 0
    },
    "max_hair_style": {
      "type": "integer",
      "default": 42
    },
    "min_hair_color": {
      "type": "integer",
      "default": 0
    },
    "max_hair_color": {
      "type": "integer",
      "default": 8
    },
    "min_cloth_color": {
      "type": "integer",
      "default": 0
    },
    "max_cloth_color": {
      "type": "integer",
      "default": 7
    },
    "min_body_style": {
      "type": "integer",
      "default": 0
    },
    "max_body_style": {
      "type": "integer",
      "default": 1
    },
    "hide_woe_damage": {
      "type": "boolean",
      "description": "When set to yes, the damage field in packets sent from woe maps will be set\nto -1, making it impossible for GMs, Bots and Hexed clients to know the\nactual damage caused by attacks. (Note 1)",
      "default": false
    },
    "pet_hair_style": {
      "type": "integer",
      "description": "\u0022hair style\u0022 number that identifies pet.\nNOTE: The client uses the \u0022hair style\u0022 field in the mob packet to tell them apart from mobs.\nThis value is always higher than the max hair-style available in said client.\nKnown values to work (all 2005 clients):\nolder sakexes: 20\nsakexe 0614: 24\nsakexe 0628 (and later): 100",
      "default": 100
    },
    "area_size": {
      "type": "integer",
      "description": "Visible area size (how many squares away from a player they can see)",
      "default": 14
    },
    "max_walk_path": {
      "type": "integer",
      "description": "Maximum walk path (how many cells a player can walk going to cursor)",
      "default": 17
    },
    "max_lv": {
      "type": "integer",
      "description": "Maximum allowed \u0027level\u0027 value that can be sent in unit packets.\nUse together with the aura_lv setting to tell when exactly to show the aura.\nNOTE: You also need to adjust the client if you want this to work.\nNOTE: Default is 99. Values above 127 will probably behave incorrectly.\nNOTE: If you don\u0027t know what this does, don\u0027t change it!!!",
      "default": 99
    },
    "aura_lv": {
      "type": "integer",
      "description": "Level required to display an aura.\nNOTE: This assumes that sending max_lv to the client will display the aura.\nNOTE: aura_lv must not be less than max_lv.\nExample: If max_lv is 99 and aura_lv is 150, characters with level 99~149\nwill be sent as being all level 98, and only characters with level\n150 or more will be reported as having level 99 and show an aura.",
      "default": 99
    },
    "client_limit_unit_lv": {
      "type": "integer",
      "description": "Units types affected by max_lv and aura_lv settings. (Note 3)\nNote: If an unit type, which normally does not show an aura, is\nset it will obtain an aura when it meets the level requirement.\nDefault: 0 (none)",
      "default": 0
    },
    "wedding_modifydisplay": {
      "type": "boolean",
      "description": "Will tuxedo and wedding dresses be shown when worn? (Note 1)",
      "default": false
    },
    "save_clothcolor": {
      "type": "boolean",
      "description": "Save Clothes color. (This will degrade performance) (Note 1)",
      "default": true
    },
    "save_body_style": {
      "type": "boolean",
      "description": "Save body styles. (Note 1)",
      "default": true
    },
    "wedding_ignorepalette": {
      "type": "boolean",
      "description": "Do not display cloth colors for the wedding class?\nNote: Both save_clothcolor and wedding_modifydisplay have to be enabled\nfor this option to take effect. Set this to yes if your cloth palettes\npack doesn\u0027t has wedding palettes (or has less than the other jobs)",
      "default": false
    },
    "xmas_ignorepalette": {
      "type": "boolean",
      "description": "Do not display cloth colors for the Xmas costume?\nSet this to yes if your cloth palettes pack doesn\u0027t have Xmas palettes (or has less than the other jobs)",
      "default": false
    },
    "summer_ignorepalette": {
      "type": "boolean",
      "description": "Do not display cloth colors for the Summer costume?\nSet this to yes if your cloth palettes pack doesn\u0027t have Summer palettes (or has less than the other jobs)",
      "default": false
    },
    "hanbok_ignorepalette": {
      "type": "boolean",
      "description": "Do not display cloth colors for the Hanbok costume?\nSet this to yes if your cloth palettes pack doesn\u0027t have Hanbok palettes (or has less than the other jobs)",
      "default": false
    },
    "oktoberfest_ignorepalette": {
      "type": "boolean",
      "description": "Do not display cloth colors for the Oktoberfest costume?\nSet this to yes if your cloth palettes pack doesn\u0027t have Oktoberfest palettes (or has less than the other jobs)",
      "default": false
    },
    "motd_type": {
      "type": "integer",
      "description": "Set this to 1 if your clients have langtype problems and can\u0027t display motd properly",
      "default": 0
    },
    "display_version": {
      "type": "boolean",
      "description": "Show rAthena version to users when the login?",
      "default": true
    },
    "display_hallucination": {
      "type": "boolean",
      "description": "When affected with the \u0022Hallucination\u0022 status effect, send the effect to client? (Note 1)\nNOTE: Set to \u0027no\u0027 if the client lags due to the \u0022Wavy\u0022 screen effect.",
      "default": true
    },
    "display_status_timers": {
      "type": "boolean",
      "description": "Set this to 1 if your client supports status change timers and you want to use them\nClients from 2009 onward support this",
      "default": true
    },
    "client_reshuffle_dice": {
      "type": "boolean",
      "description": "Randomizes the dice emoticon server-side, to prevent clients from forging\npackets for the desired number. (Note 1)",
      "default": true
    },
    "client_sort_storage": {
      "type": "boolean",
      "description": "Sorts the cart, guild storage, inventory and storage before it is sent to the client. (Note 1)\nOfficial servers do not sort them.\nNOTE: Enabling this option degrades performance.",
      "default": false
    },
    "update_enemy_position": {
      "type": "boolean",
      "description": "Update enemy position while in invisible state? (Note 1)\nNOTE: Set to \u0027no\u0027 will make client won\u0027t update enemy position unless the players have \u0022Intravision\u0022 effect.\nSo that will help client handling WPE - Maya Purple Hack stuff.\nBut it will screw \u0027the game animation display\u0027 while players in invisible state.",
      "default": true
    },
    "spawn_direction": {
      "type": "boolean",
      "description": "When a player teleports, changes maps, or logs in, will they face the direction they were facing before warped?\nOfficial: Disabled, players always face North.",
      "default": false
    },
    "mvp_exp_reward_message": {
      "type": "boolean",
      "description": "Show the MVP EXP reward message for clients 2013-12-23cRagexe and newer? (Note 1)\nkRO removed the packet and this re-enables the message.\nOfficial: Disabled.",
      "default": false
    },
    "ping_timer_inverval": {
      "type": "integer",
      "description": "Send ping timer\nInterval in seconds for each timer invoke.",
      "default": 30
    },
    "ping_time": {
      "type": "integer",
      "description": "Send packets timeout in seconds before ping packet can be sent.",
      "default": 20
    },
    "show_skill_scale": {
      "type": "boolean",
      "description": "Show skill scale for clients 2015-12-23 and newer? (Note 1)\nOfficial: yes",
      "default": true
    },
    "drop_connection_on_quit": {
      "type": "boolean",
      "description": "Should the connection be dropped on server side after a player disconnection request was received? (Note 1)\nNote: Enabling this is known to cause problems on clients that make use of REST API calls.\nOfficial: no",
      "default": false
    },
    "macro_detection_retry": {
      "type": "integer",
      "description": "Macro Detector retries\nNumber of times someone can fail the macro detection before being banned.\nOfficial: 3 (minimum: 1)",
      "default": 3
    },
    "macro_detection_timeout": {
      "type": "integer",
      "description": "Macro Detector timeout\nAmount of time in milliseconds before the macro detection will fail and the user will be banned.\nOfficial: 60000",
      "default": 60000
    },
    "macro_detection_punishment": {
      "type": "integer",
      "description": "Macro Detector punishment type\n0 - Ban\n1 - Jail\nOfficial: 0",
      "default": 0
    },
    "macro_detection_punishment_time": {
      "type": "integer",
      "description": "Macro Detector punishment duration\nAmount of time in minutes that the punishment type is active for. Use 0 for infinite.\nOfficial: 0",
      "default": 0
    },
    "macrochecker_delay": {
      "type": "integer",
      "description": "Macrochecker delay (per map)\nSet to 0 to disable",
      "default": 600000
    }
  }
}

=== Danil0v3s/mmo-csharp/Map.Server/config/battle/client.json
{
  "$schema": "./client.schema.json",
  "min_chat_delay": 0,
  "min_hair_style": 0,
  "max_hair_style": 42,
  "min_hair_color": 0,
  "max_hair_color": 8,
  "min_cloth_color": 0,
  "max_cloth_color": 7,
  "min_body_style": 0,
  "max_body_style": 1,
  "hide_woe_damage": false,
  "pet_hair_style": 100,
  "area_size": 14,
  "max_walk_path": 17,
  "max_lv": 99,
  "aura_lv": 99,
  "client_limit_unit_lv": 0,
  "wedding_modifydisplay": false,
  "save_clothcolor": true,
  "save_body_style": true,
  "wedding_ignorepalette": false,
  "xmas_ignorepalette": false,
  "summer_ignorepalette": false,
  "hanbok_ignorepalette": false,
  "oktoberfest_ignorepalette": false,
  "motd_type": 0,
  "display_version": true,
  "display_hallucination": true,
  "display_status_timers": true,
  "client_reshuffle_dice": true,
  "client_sort_storage": false,
  "update_enemy_position": true,
  "spawn_direction": false,
  "mvp_exp_reward_message": false,
  "ping_timer_inverval": 30,
  "ping_time": 20,
  "show_skill_scale": true,
  "drop_connection_on_quit": false,
  "macro_detection_retry": 3,
  "macro_detection_timeout": 60000,
  "macro_detection_punishment": 0,
  "macro_detection_punishment_time": 0,
  "macrochecker_delay": 600000
}
